### ISSUE TITLE
hi .. ane download error

### ISSUE THREAD

**Issue by nuto83** [tuarua/Zip-ANE#12]
I ran get_dependencies.ps1 with powershell.
There is no file path.
Can I get ane files?

return 
====================================================
+ get_dependencies.ps1
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (get_dependencies.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by tuarua** [comment]
please do a git pull and run again.
I have fixed a bug in the ps1 file

**Comment by nuto83** [comment]
> please do a git pull and run again.
> I have fixed a bug in the ps1 file

Thank you very much!!
