### ISSUE TITLE
animate CC,

### ISSUE THREAD

**Issue by nuto83** [tuarua/Zip-ANE#13]
Hi again
i did follow your guide for windows
but, i can't extract from zip file
and when i created compressed file , it was an empty file
do you have another expected checklist ?
thank you!!

**Comment by tuarua** [comment]
Compressing and extracting zip files are working for me.
Please create a fork which shows **exactly** how to reproduce, uncluding the files you are trying to use

**Comment by nuto83** [comment]
oh, yes
i will try again, be carefully
the code is not diffrent.
Do i need to copy the .dll file to the system32 and SysWOW64 folder?
what version of the Adobe AIR your installed?

**Comment by nuto83** [comment]
the Adobe AIR version installed on my pc is 32.0.0.89
im not updating yet because of  the problem of new version video play

**Comment by nuto83** [comment]
it is solved. in the update 
thank you for your attention
