### ISSUE TITLE
Extracting the folders with in the compressed file

### ISSUE THREAD

**Issue by nuto83** [tuarua/Zip-ANE#15]
An error occurs when extracting compressed files with folders inside.
thank you

![20190603_153448](https://user-images.githubusercontent.com/37373643/58781436-cd1ad100-8616-11e9-93a6-583834c09b42.png)
![20190603_153500](https://user-images.githubusercontent.com/37373643/58781438-cdb36780-8616-11e9-8b07-1aa37b8f870c.png)

**Comment by tuarua** [comment]
A screen grab is no use. I only speak English so I have no idea what it says.
You need to provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) based on the sample project included with the repo.
Do not open any more tickets without doing this.

Put a try{}catch{} around your code and inspect the error that is thrown.

**Comment by tuarua** [comment]
no response - closing
