### ISSUE TITLE
Incorrect folder structure of created ZIP file

### ISSUE THREAD

**Issue by subdan** [tuarua/Zip-ANE#4]
Try to compress File.applicationStorageDirectory. The ZIP file will contains only pointer to previous folder.
![screenshot_1](https://user-images.githubusercontent.com/410293/41962417-4bafae7a-79f5-11e8-8f41-aca137470ae1.png)
AIR 30, Android 5.0

**Comment by subdan** [comment]
I tried to compress File.applicationStorageDirectory.resolvePath("someDirectoryWithFiles") and the ZIP archive also broken.

**Comment by tuarua** [comment]
There is a newer version now.

**Comment by subdan** [comment]
Now it works as expected.
